[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "AI4Europe"
authors = [{name = "Andrea Borghesi", email = "andrea.borghesi3@unibo.it"}]
dynamic = ["version", "description"]
